project:
  type: website
  preview:
    port: 4200

website:
  page-navigation: true
  title: "Estatística Sem Firulas"
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/). License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/
      - icon: envelope
        href: mailto:m@gmail.com
  twitter-card:
    creator: "@pudim"
    card-style: summary_large_image
  navbar:
    right:
      - about.qmd
      - text: Posts
        menu:
          - text: All posts
            href: posts/index.qmd
          - text: English
            href: posts/en.qmd
          - text: Português
            href: posts/pt.qmd
          - text: Español
            href: posts/es.qmd

      - text: Series
        menu:
          - text: GitHub Actions
            href: series-gha.qmd
      - text: Talks
        menu:
          - text: All/Todas
            href: talks/index.qmd
          - text: English
            href: talks/en/index.qmd
          - text: Português
            href: talks/pt/index.qmd
          - text: Español
            href: talks/es/index.qmd
      - quarto.qmd
      - videos.qmd
      - text: Resume
        href: http://pudim.com.br/
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/

format:
  html:
    smooth-scroll: true
    theme: journal
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.pudim\.com\/**'
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true

editor: visual

comments:
  giscus:
    repo: pudim/blog-en

execute:
  freeze: true
